### PR TITLE
[iOS] support reading Library files instead of assets-library://

### PR DESCRIPTION
**Pull request by cuongchau93**
[refactor] JS part: support dominant color hex to be same key for both ios and android

### CODE REVIEW

**Comment by chetstone** [comment]
Thanks for your contribution! I apologize for not having a [Contributing](https://github.com/chetstone/react-native-palette#contributing) section in my README. I just added one. Would you kindly review my requests there and resubmit the PR? 
Thanks so much.

**Comment by chetstone** [comment]
Also one question: does this fix Issue #12 for iOS?

**Comment by cuongchau93** [comment]
> Thanks for your contribution! I apologize for not having a [Contributing](https://github.com/chetstone/react-native-palette#contributing) section in my README. I just added one. Would you kindly review my requests there and resubmit the PR?
> Thanks so much.

Sure, will do

> Also one question: does this fix Issue #12 for iOS?

No, this does not fix that issue, 
Currently if we run the example app in ios we will run into getColors of null as below 
Screen Shot 2020-05-02 at 14 48 11

With this PR change, it will fix that issue

Also in this PR (index.js), I added HEX property in response object
for Android, only the first swatches has that HEX property

**Comment by cuongchau93** [comment]
the change in this PR breaks the support of library image in ios, because in my case i didnt need it, 
I will try make it supports both 
Close the PR for now

**Comment by cuongchau93** [comment]
@chetstone before opening another PR, i want to ask if my changes is needed
in ios it currently only support asset with path 
assets-library://asset/asset.JPG?id=B84E8479-475C-4727-A4A4-B77AA9980897&ext=JPG
if we supply it with uri file path such as 
/Users/cuongchau93/Library/Developer/CoreSimulator/Devices/C1105148-CD13-4EB7-98DB-B2A631B5B46E/data/Containers/Data/Application/A298452C-613C-46B0-BC9B-11FDD1475C1B/tmp/DEFA99E7-CA1F-4A77-A16B-4321CDCE3DA8.jpg

it does not work
If this change is needed, I will raise another PR

**Comment by chetstone** [comment]
Hi, thanks very much for responding. Unfortunately I do not have time to
look into this this week. I will followup with answers to your questions
next week.

Thanks again.

**Pull request closed without merging**
